info_table_cb:
	; CB00
	dd      offset compCB00
	db      (offset compCB00_end)-(offset compCB00)
	db      0,0,0
	; CB01
	dd      offset compCB01
	db      (offset compCB01_end)-(offset compCB01)
	db      0,0,0
	; CB02
	dd      offset compCB02
	db      (offset compCB02_end)-(offset compCB02)
	db      0,0,0
	; CB03
	dd      offset compCB03
	db      (offset compCB03_end)-(offset compCB03)
	db      0,0,0
	; CB04
	dd      offset compCB04
	db      (offset compCB04_end)-(offset compCB04)
	db      0,0,0
	; CB05
	dd      offset compCB05
	db      (offset compCB05_end)-(offset compCB05)
	db      0,0,0
	; CB06
	dd      offset compCB06
	db      (offset compCB06_end)-(offset compCB06)
	db      0,0,0
	; CB07
	dd      offset compCB07
	db      (offset compCB07_end)-(offset compCB07)
	db      0,0,0
	; CB08
	dd      offset compCB08
	db      (offset compCB08_end)-(offset compCB08)
	db      0,0,0
	; CB09
	dd      offset compCB09
	db      (offset compCB09_end)-(offset compCB09)
	db      0,0,0
	; CB0A
	dd      offset compCB0A
	db      (offset compCB0A_end)-(offset compCB0A)
	db      0,0,0
	; CB0B
	dd      offset compCB0B
	db      (offset compCB0B_end)-(offset compCB0B)
	db      0,0,0
	; CB0C
	dd      offset compCB0C
	db      (offset compCB0C_end)-(offset compCB0C)
	db      0,0,0
	; CB0D
	dd      offset compCB0D
	db      (offset compCB0D_end)-(offset compCB0D)
	db      0,0,0
	; CB0E
	dd      offset compCB0E
	db      (offset compCB0E_end)-(offset compCB0E)
	db      0,0,0
	; CB0F
	dd      offset compCB0F
	db      (offset compCB0F_end)-(offset compCB0F)
	db      0,0,0
	; CB10
	dd      offset compCB10
	db      (offset compCB10_end)-(offset compCB10)
	db      0,0,0
	; CB11
	dd      offset compCB11
	db      (offset compCB11_end)-(offset compCB11)
	db      0,0,0
	; CB12
	dd      offset compCB12
	db      (offset compCB12_end)-(offset compCB12)
	db      0,0,0
	; CB13
	dd      offset compCB13
	db      (offset compCB13_end)-(offset compCB13)
	db      0,0,0
	; CB14
	dd      offset compCB14
	db      (offset compCB14_end)-(offset compCB14)
	db      0,0,0
	; CB15
	dd      offset compCB15
	db      (offset compCB15_end)-(offset compCB15)
	db      0,0,0
	; CB16
	dd      offset compCB16
	db      (offset compCB16_end)-(offset compCB16)
	db      0,0,0
	; CB17
	dd      offset compCB17
	db      (offset compCB17_end)-(offset compCB17)
	db      0,0,0
	; CB18
	dd      offset compCB18
	db      (offset compCB18_end)-(offset compCB18)
	db      0,0,0
	; CB19
	dd      offset compCB19
	db      (offset compCB19_end)-(offset compCB19)
	db      0,0,0
	; CB1A
	dd      offset compCB1A
	db      (offset compCB1A_end)-(offset compCB1A)
	db      0,0,0
	; CB1B
	dd      offset compCB1B
	db      (offset compCB1B_end)-(offset compCB1B)
	db      0,0,0
	; CB1C
	dd      offset compCB1C
	db      (offset compCB1C_end)-(offset compCB1C)
	db      0,0,0
	; CB1D
	dd      offset compCB1D
	db      (offset compCB1D_end)-(offset compCB1D)
	db      0,0,0
	; CB1E
	dd      offset compCB1E
	db      (offset compCB1E_end)-(offset compCB1E)
	db      0,0,0
	; CB1F
	dd      offset compCB1F
	db      (offset compCB1F_end)-(offset compCB1F)
	db      0,0,0
	; CB20
	dd      offset compCB20
	db      (offset compCB20_end)-(offset compCB20)
	db      0,0,0
	; CB21
	dd      offset compCB21
	db      (offset compCB21_end)-(offset compCB21)
	db      0,0,0
	; CB22
	dd      offset compCB22
	db      (offset compCB22_end)-(offset compCB22)
	db      0,0,0
	; CB23
	dd      offset compCB23
	db      (offset compCB23_end)-(offset compCB23)
	db      0,0,0
	; CB24
	dd      offset compCB24
	db      (offset compCB24_end)-(offset compCB24)
	db      0,0,0
	; CB25
	dd      offset compCB25
	db      (offset compCB25_end)-(offset compCB25)
	db      0,0,0
	; CB26
	dd      offset compCB26
	db      (offset compCB26_end)-(offset compCB26)
	db      0,0,0
	; CB27
	dd      offset compCB27
	db      (offset compCB27_end)-(offset compCB27)
	db      0,0,0
	; CB28
	dd      offset compCB28
	db      (offset compCB28_end)-(offset compCB28)
	db      0,0,0
	; CB29
	dd      offset compCB29
	db      (offset compCB29_end)-(offset compCB29)
	db      0,0,0
	; CB2A
	dd      offset compCB2A
	db      (offset compCB2A_end)-(offset compCB2A)
	db      0,0,0
	; CB2B
	dd      offset compCB2B
	db      (offset compCB2B_end)-(offset compCB2B)
	db      0,0,0
	; CB2C
	dd      offset compCB2C
	db      (offset compCB2C_end)-(offset compCB2C)
	db      0,0,0
	; CB2D
	dd      offset compCB2D
	db      (offset compCB2D_end)-(offset compCB2D)
	db      0,0,0
	; CB2E
	dd      offset compCB2E
	db      (offset compCB2E_end)-(offset compCB2E)
	db      0,0,0
	; CB2F
	dd      offset compCB2F
	db      (offset compCB2F_end)-(offset compCB2F)
	db      0,0,0
	; CB30
	dd      0; offset compCB30
	db      0; (offset compCB30_end)-(offset compCB30)
	db      0,0,0
	; CB31
	dd      0; offset compCB31
	db      0; (offset compCB31_end)-(offset compCB31)
	db      0,0,0
	; CB32
	dd      0; offset compCB32
	db      0; (offset compCB32_end)-(offset compCB32)
	db      0,0,0
	; CB33
	dd      0; offset compCB33
	db      0; (offset compCB33_end)-(offset compCB33)
	db      0,0,0
	; CB34
	dd      0; offset compCB34
	db      0; (offset compCB34_end)-(offset compCB34)
	db      0,0,0
	; CB35
	dd      0; offset compCB35
	db      0; (offset compCB35_end)-(offset compCB35)
	db      0,0,0
	; CB36
	dd      0; offset compCB36
	db      0; (offset compCB36_end)-(offset compCB36)
	db      0,0,0
	; CB37
	dd      0; offset compCB37
	db      0; (offset compCB37_end)-(offset compCB37)
	db      0,0,0
	; CB38
	dd      offset compCB38
	db      (offset compCB38_end)-(offset compCB38)
	db      0,0,0
	; CB39
	dd      offset compCB39
	db      (offset compCB39_end)-(offset compCB39)
	db      0,0,0
	; CB3A
	dd      offset compCB3A
	db      (offset compCB3A_end)-(offset compCB3A)
	db      0,0,0
	; CB3B
	dd      offset compCB3B
	db      (offset compCB3B_end)-(offset compCB3B)
	db      0,0,0
	; CB3C
	dd      offset compCB3C
	db      (offset compCB3C_end)-(offset compCB3C)
	db      0,0,0
	; CB3D
	dd      offset compCB3D
	db      (offset compCB3D_end)-(offset compCB3D)
	db      0,0,0
	; CB3E
	dd      offset compCB3E
	db      (offset compCB3E_end)-(offset compCB3E)
	db      0,0,0
	; CB3F
	dd      offset compCB3F
	db      (offset compCB3F_end)-(offset compCB3F)
	db      0,0,0
	; CB40
	dd      offset compCB40
	db      (offset compCB40_end)-(offset compCB40)
	db      0,0,0
	; CB41
	dd      offset compCB41
	db      (offset compCB41_end)-(offset compCB41)
	db      0,0,0
	; CB42
	dd      offset compCB42
	db      (offset compCB42_end)-(offset compCB42)
	db      0,0,0
	; CB43
	dd      offset compCB43
	db      (offset compCB43_end)-(offset compCB43)
	db      0,0,0
	; CB44
	dd      offset compCB44
	db      (offset compCB44_end)-(offset compCB44)
	db      0,0,0
	; CB45
	dd      offset compCB45
	db      (offset compCB45_end)-(offset compCB45)
	db      0,0,0
	; CB46
	dd      offset compCB46
	db      (offset compCB46_end)-(offset compCB46)
	db      0,0,0
	; CB47
	dd      offset compCB47
	db      (offset compCB47_end)-(offset compCB47)
	db      0,0,0
	; CB48
	dd      offset compCB48
	db      (offset compCB48_end)-(offset compCB48)
	db      0,0,0
	; CB49
	dd      offset compCB49
	db      (offset compCB49_end)-(offset compCB49)
	db      0,0,0
	; CB4A
	dd      offset compCB4A
	db      (offset compCB4A_end)-(offset compCB4A)
	db      0,0,0
	; CB4B
	dd      offset compCB4B
	db      (offset compCB4B_end)-(offset compCB4B)
	db      0,0,0
	; CB4C
	dd      offset compCB4C
	db      (offset compCB4C_end)-(offset compCB4C)
	db      0,0,0
	; CB4D
	dd      offset compCB4D
	db      (offset compCB4D_end)-(offset compCB4D)
	db      0,0,0
	; CB4E
	dd      offset compCB4E
	db      (offset compCB4E_end)-(offset compCB4E)
	db      0,0,0
	; CB4F
	dd      offset compCB4F
	db      (offset compCB4F_end)-(offset compCB4F)
	db      0,0,0
	; CB50
	dd      offset compCB50
	db      (offset compCB50_end)-(offset compCB50)
	db      0,0,0
	; CB51
	dd      offset compCB51
	db      (offset compCB51_end)-(offset compCB51)
	db      0,0,0
	; CB52
	dd      offset compCB52
	db      (offset compCB52_end)-(offset compCB52)
	db      0,0,0
	; CB53
	dd      offset compCB53
	db      (offset compCB53_end)-(offset compCB53)
	db      0,0,0
	; CB54
	dd      offset compCB54
	db      (offset compCB54_end)-(offset compCB54)
	db      0,0,0
	; CB55
	dd      offset compCB55
	db      (offset compCB55_end)-(offset compCB55)
	db      0,0,0
	; CB56
	dd      offset compCB56
	db      (offset compCB56_end)-(offset compCB56)
	db      0,0,0
	; CB57
	dd      offset compCB57
	db      (offset compCB57_end)-(offset compCB57)
	db      0,0,0
	; CB58
	dd      offset compCB58
	db      (offset compCB58_end)-(offset compCB58)
	db      0,0,0
	; CB59
	dd      offset compCB59
	db      (offset compCB59_end)-(offset compCB59)
	db      0,0,0
	; CB5A
	dd      offset compCB5A
	db      (offset compCB5A_end)-(offset compCB5A)
	db      0,0,0
	; CB5B
	dd      offset compCB5B
	db      (offset compCB5B_end)-(offset compCB5B)
	db      0,0,0
	; CB5C
	dd      offset compCB5C
	db      (offset compCB5C_end)-(offset compCB5C)
	db      0,0,0
	; CB5D
	dd      offset compCB5D
	db      (offset compCB5D_end)-(offset compCB5D)
	db      0,0,0
	; CB5E
	dd      offset compCB5E
	db      (offset compCB5E_end)-(offset compCB5E)
	db      0,0,0
	; CB5F
	dd      offset compCB5F
	db      (offset compCB5F_end)-(offset compCB5F)
	db      0,0,0
	; CB60
	dd      offset compCB60
	db      (offset compCB60_end)-(offset compCB60)
	db      0,0,0
	; CB61
	dd      offset compCB61
	db      (offset compCB61_end)-(offset compCB61)
	db      0,0,0
	; CB62
	dd      offset compCB62
	db      (offset compCB62_end)-(offset compCB62)
	db      0,0,0
	; CB63
	dd      offset compCB63
	db      (offset compCB63_end)-(offset compCB63)
	db      0,0,0
	; CB64
	dd      offset compCB64
	db      (offset compCB64_end)-(offset compCB64)
	db      0,0,0
	; CB65
	dd      offset compCB65
	db      (offset compCB65_end)-(offset compCB65)
	db      0,0,0
	; CB66
	dd      offset compCB66
	db      (offset compCB66_end)-(offset compCB66)
	db      0,0,0
	; CB67
	dd      offset compCB67
	db      (offset compCB67_end)-(offset compCB67)
	db      0,0,0
	; CB68
	dd      offset compCB68
	db      (offset compCB68_end)-(offset compCB68)
	db      0,0,0
	; CB69
	dd      offset compCB69
	db      (offset compCB69_end)-(offset compCB69)
	db      0,0,0
	; CB6A
	dd      offset compCB6A
	db      (offset compCB6A_end)-(offset compCB6A)
	db      0,0,0
	; CB6B
	dd      offset compCB6B
	db      (offset compCB6B_end)-(offset compCB6B)
	db      0,0,0
	; CB6C
	dd      offset compCB6C
	db      (offset compCB6C_end)-(offset compCB6C)
	db      0,0,0
	; CB6D
	dd      offset compCB6D
	db      (offset compCB6D_end)-(offset compCB6D)
	db      0,0,0
	; CB6E
	dd      offset compCB6E
	db      (offset compCB6E_end)-(offset compCB6E)
	db      0,0,0
	; CB6F
	dd      offset compCB6F
	db      (offset compCB6F_end)-(offset compCB6F)
	db      0,0,0
	; CB70
	dd      offset compCB70
	db      (offset compCB70_end)-(offset compCB70)
	db      0,0,0
	; CB71
	dd      offset compCB71
	db      (offset compCB71_end)-(offset compCB71)
	db      0,0,0
	; CB72
	dd      offset compCB72
	db      (offset compCB72_end)-(offset compCB72)
	db      0,0,0
	; CB73
	dd      offset compCB73
	db      (offset compCB73_end)-(offset compCB73)
	db      0,0,0
	; CB74
	dd      offset compCB74
	db      (offset compCB74_end)-(offset compCB74)
	db      0,0,0
	; CB75
	dd      offset compCB75
	db      (offset compCB75_end)-(offset compCB75)
	db      0,0,0
	; CB76
	dd      offset compCB76
	db      (offset compCB76_end)-(offset compCB76)
	db      0,0,0
	; CB77
	dd      offset compCB77
	db      (offset compCB77_end)-(offset compCB77)
	db      0,0,0
	; CB78
	dd      offset compCB78
	db      (offset compCB78_end)-(offset compCB78)
	db      0,0,0
	; CB79
	dd      offset compCB79
	db      (offset compCB79_end)-(offset compCB79)
	db      0,0,0
	; CB7A
	dd      offset compCB7A
	db      (offset compCB7A_end)-(offset compCB7A)
	db      0,0,0
	; CB7B
	dd      offset compCB7B
	db      (offset compCB7B_end)-(offset compCB7B)
	db      0,0,0
	; CB7C
	dd      offset compCB7C
	db      (offset compCB7C_end)-(offset compCB7C)
	db      0,0,0
	; CB7D
	dd      offset compCB7D
	db      (offset compCB7D_end)-(offset compCB7D)
	db      0,0,0
	; CB7E
	dd      offset compCB7E
	db      (offset compCB7E_end)-(offset compCB7E)
	db      0,0,0
	; CB7F
	dd      offset compCB7F
	db      (offset compCB7F_end)-(offset compCB7F)
	db      0,0,0
	; CB80
	dd      offset compCB80
	db      (offset compCB80_end)-(offset compCB80)
	db      0,0,0
	; CB81
	dd      offset compCB81
	db      (offset compCB81_end)-(offset compCB81)
	db      0,0,0
	; CB82
	dd      offset compCB82
	db      (offset compCB82_end)-(offset compCB82)
	db      0,0,0
	; CB83
	dd      offset compCB83
	db      (offset compCB83_end)-(offset compCB83)
	db      0,0,0
	; CB84
	dd      offset compCB84
	db      (offset compCB84_end)-(offset compCB84)
	db      0,0,0
	; CB85
	dd      offset compCB85
	db      (offset compCB85_end)-(offset compCB85)
	db      0,0,0
	; CB86
	dd      offset compCB86
	db      (offset compCB86_end)-(offset compCB86)
	db      0,0,0
	; CB87
	dd      offset compCB87
	db      (offset compCB87_end)-(offset compCB87)
	db      0,0,0
	; CB88
	dd      offset compCB88
	db      (offset compCB88_end)-(offset compCB88)
	db      0,0,0
	; CB89
	dd      offset compCB89
	db      (offset compCB89_end)-(offset compCB89)
	db      0,0,0
	; CB8A
	dd      offset compCB8A
	db      (offset compCB8A_end)-(offset compCB8A)
	db      0,0,0
	; CB8B
	dd      offset compCB8B
	db      (offset compCB8B_end)-(offset compCB8B)
	db      0,0,0
	; CB8C
	dd      offset compCB8C
	db      (offset compCB8C_end)-(offset compCB8C)
	db      0,0,0
	; CB8D
	dd      offset compCB8D
	db      (offset compCB8D_end)-(offset compCB8D)
	db      0,0,0
	; CB8E
	dd      offset compCB8E
	db      (offset compCB8E_end)-(offset compCB8E)
	db      0,0,0
	; CB8F
	dd      offset compCB8F
	db      (offset compCB8F_end)-(offset compCB8F)
	db      0,0,0
	; CB90
	dd      offset compCB90
	db      (offset compCB90_end)-(offset compCB90)
	db      0,0,0
	; CB91
	dd      offset compCB91
	db      (offset compCB91_end)-(offset compCB91)
	db      0,0,0
	; CB92
	dd      offset compCB92
	db      (offset compCB92_end)-(offset compCB92)
	db      0,0,0
	; CB93
	dd      offset compCB93
	db      (offset compCB93_end)-(offset compCB93)
	db      0,0,0
	; CB94
	dd      offset compCB94
	db      (offset compCB94_end)-(offset compCB94)
	db      0,0,0
	; CB95
	dd      offset compCB95
	db      (offset compCB95_end)-(offset compCB95)
	db      0,0,0
	; CB96
	dd      offset compCB96
	db      (offset compCB96_end)-(offset compCB96)
	db      0,0,0
	; CB97
	dd      offset compCB97
	db      (offset compCB97_end)-(offset compCB97)
	db      0,0,0
	; CB98
	dd      offset compCB98
	db      (offset compCB98_end)-(offset compCB98)
	db      0,0,0
	; CB99
	dd      offset compCB99
	db      (offset compCB99_end)-(offset compCB99)
	db      0,0,0
	; CB9A
	dd      offset compCB9A
	db      (offset compCB9A_end)-(offset compCB9A)
	db      0,0,0
	; CB9B
	dd      offset compCB9B
	db      (offset compCB9B_end)-(offset compCB9B)
	db      0,0,0
	; CB9C
	dd      offset compCB9C
	db      (offset compCB9C_end)-(offset compCB9C)
	db      0,0,0
	; CB9D
	dd      offset compCB9D
	db      (offset compCB9D_end)-(offset compCB9D)
	db      0,0,0
	; CB9E
	dd      offset compCB9E
	db      (offset compCB9E_end)-(offset compCB9E)
	db      0,0,0
	; CB9F
	dd      offset compCB9F
	db      (offset compCB9F_end)-(offset compCB9F)
	db      0,0,0
	; CBA0
	dd      offset compCBA0
	db      (offset compCBA0_end)-(offset compCBA0)
	db      0,0,0
	; CBA1
	dd      offset compCBA1
	db      (offset compCBA1_end)-(offset compCBA1)
	db      0,0,0
	; CBA2
	dd      offset compCBA2
	db      (offset compCBA2_end)-(offset compCBA2)
	db      0,0,0
	; CBA3
	dd      offset compCBA3
	db      (offset compCBA3_end)-(offset compCBA3)
	db      0,0,0
	; CBA4
	dd      offset compCBA4
	db      (offset compCBA4_end)-(offset compCBA4)
	db      0,0,0
	; CBA5
	dd      offset compCBA5
	db      (offset compCBA5_end)-(offset compCBA5)
	db      0,0,0
	; CBA6
	dd      offset compCBA6
	db      (offset compCBA6_end)-(offset compCBA6)
	db      0,0,0
	; CBA7
	dd      offset compCBA7
	db      (offset compCBA7_end)-(offset compCBA7)
	db      0,0,0
	; CBA8
	dd      offset compCBA8
	db      (offset compCBA8_end)-(offset compCBA8)
	db      0,0,0
	; CBA9
	dd      offset compCBA9
	db      (offset compCBA9_end)-(offset compCBA9)
	db      0,0,0
	; CBAA
	dd      offset compCBAA
	db      (offset compCBAA_end)-(offset compCBAA)
	db      0,0,0
	; CBAB
	dd      offset compCBAB
	db      (offset compCBAB_end)-(offset compCBAB)
	db      0,0,0
	; CBAC
	dd      offset compCBAC
	db      (offset compCBAC_end)-(offset compCBAC)
	db      0,0,0
	; CBAD
	dd      offset compCBAD
	db      (offset compCBAD_end)-(offset compCBAD)
	db      0,0,0
	; CBAE
	dd      offset compCBAE
	db      (offset compCBAE_end)-(offset compCBAE)
	db      0,0,0
	; CBAF
	dd      offset compCBAF
	db      (offset compCBAF_end)-(offset compCBAF)
	db      0,0,0
	; CBB0
	dd      offset compCBB0
	db      (offset compCBB0_end)-(offset compCBB0)
	db      0,0,0
	; CBB1
	dd      offset compCBB1
	db      (offset compCBB1_end)-(offset compCBB1)
	db      0,0,0
	; CBB2
	dd      offset compCBB2
	db      (offset compCBB2_end)-(offset compCBB2)
	db      0,0,0
	; CBB3
	dd      offset compCBB3
	db      (offset compCBB3_end)-(offset compCBB3)
	db      0,0,0
	; CBB4
	dd      offset compCBB4
	db      (offset compCBB4_end)-(offset compCBB4)
	db      0,0,0
	; CBB5
	dd      offset compCBB5
	db      (offset compCBB5_end)-(offset compCBB5)
	db      0,0,0
	; CBB6
	dd      offset compCBB6
	db      (offset compCBB6_end)-(offset compCBB6)
	db      0,0,0
	; CBB7
	dd      offset compCBB7
	db      (offset compCBB7_end)-(offset compCBB7)
	db      0,0,0
	; CBB8
	dd      offset compCBB8
	db      (offset compCBB8_end)-(offset compCBB8)
	db      0,0,0
	; CBB9
	dd      offset compCBB9
	db      (offset compCBB9_end)-(offset compCBB9)
	db      0,0,0
	; CBBA
	dd      offset compCBBA
	db      (offset compCBBA_end)-(offset compCBBA)
	db      0,0,0
	; CBBB
	dd      offset compCBBB
	db      (offset compCBBB_end)-(offset compCBBB)
	db      0,0,0
	; CBBC
	dd      offset compCBBC
	db      (offset compCBBC_end)-(offset compCBBC)
	db      0,0,0
	; CBBD
	dd      offset compCBBD
	db      (offset compCBBD_end)-(offset compCBBD)
	db      0,0,0
	; CBBE
	dd      offset compCBBE
	db      (offset compCBBE_end)-(offset compCBBE)
	db      0,0,0
	; CBBF
	dd      offset compCBBF
	db      (offset compCBBF_end)-(offset compCBBF)
	db      0,0,0
	; CBC0
	dd      offset compCBC0
	db      (offset compCBC0_end)-(offset compCBC0)
	db      0,0,0
	; CBC1
	dd      offset compCBC1
	db      (offset compCBC1_end)-(offset compCBC1)
	db      0,0,0
	; CBC2
	dd      offset compCBC2
	db      (offset compCBC2_end)-(offset compCBC2)
	db      0,0,0
	; CBC3
	dd      offset compCBC3
	db      (offset compCBC3_end)-(offset compCBC3)
	db      0,0,0
	; CBC4
	dd      offset compCBC4
	db      (offset compCBC4_end)-(offset compCBC4)
	db      0,0,0
	; CBC5
	dd      offset compCBC5
	db      (offset compCBC5_end)-(offset compCBC5)
	db      0,0,0
	; CBC6
	dd      offset compCBC6
	db      (offset compCBC6_end)-(offset compCBC6)
	db      0,0,0
	; CBC7
	dd      offset compCBC7
	db      (offset compCBC7_end)-(offset compCBC7)
	db      0,0,0
	; CBC8
	dd      offset compCBC8
	db      (offset compCBC8_end)-(offset compCBC8)
	db      0,0,0
	; CBC9
	dd      offset compCBC9
	db      (offset compCBC9_end)-(offset compCBC9)
	db      0,0,0
	; CBCA
	dd      offset compCBCA
	db      (offset compCBCA_end)-(offset compCBCA)
	db      0,0,0
	; CBCB
	dd      offset compCBCB
	db      (offset compCBCB_end)-(offset compCBCB)
	db      0,0,0
	; CBCC
	dd      offset compCBCC
	db      (offset compCBCC_end)-(offset compCBCC)
	db      0,0,0
	; CBCD
	dd      offset compCBCD
	db      (offset compCBCD_end)-(offset compCBCD)
	db      0,0,0
	; CBCE
	dd      offset compCBCE
	db      (offset compCBCE_end)-(offset compCBCE)
	db      0,0,0
	; CBCF
	dd      offset compCBCF
	db      (offset compCBCF_end)-(offset compCBCF)
	db      0,0,0
	; CBD0
	dd      offset compCBD0
	db      (offset compCBD0_end)-(offset compCBD0)
	db      0,0,0
	; CBD1
	dd      offset compCBD1
	db      (offset compCBD1_end)-(offset compCBD1)
	db      0,0,0
	; CBD2
	dd      offset compCBD2
	db      (offset compCBD2_end)-(offset compCBD2)
	db      0,0,0
	; CBD3
	dd      offset compCBD3
	db      (offset compCBD3_end)-(offset compCBD3)
	db      0,0,0
	; CBD4
	dd      offset compCBD4
	db      (offset compCBD4_end)-(offset compCBD4)
	db      0,0,0
	; CBD5
	dd      offset compCBD5
	db      (offset compCBD5_end)-(offset compCBD5)
	db      0,0,0
	; CBD6
	dd      offset compCBD6
	db      (offset compCBD6_end)-(offset compCBD6)
	db      0,0,0
	; CBD7
	dd      offset compCBD7
	db      (offset compCBD7_end)-(offset compCBD7)
	db      0,0,0
	; CBD8
	dd      offset compCBD8
	db      (offset compCBD8_end)-(offset compCBD8)
	db      0,0,0
	; CBD9
	dd      offset compCBD9
	db      (offset compCBD9_end)-(offset compCBD9)
	db      0,0,0
	; CBDA
	dd      offset compCBDA
	db      (offset compCBDA_end)-(offset compCBDA)
	db      0,0,0
	; CBDB
	dd      offset compCBDB
	db      (offset compCBDB_end)-(offset compCBDB)
	db      0,0,0
	; CBDC
	dd      offset compCBDC
	db      (offset compCBDC_end)-(offset compCBDC)
	db      0,0,0
	; CBDD
	dd      offset compCBDD
	db      (offset compCBDD_end)-(offset compCBDD)
	db      0,0,0
	; CBDE
	dd      offset compCBDE
	db      (offset compCBDE_end)-(offset compCBDE)
	db      0,0,0
	; CBDF
	dd      offset compCBDF
	db      (offset compCBDF_end)-(offset compCBDF)
	db      0,0,0
	; CBE0
	dd      offset compCBE0
	db      (offset compCBE0_end)-(offset compCBE0)
	db      0,0,0
	; CBE1
	dd      offset compCBE1
	db      (offset compCBE1_end)-(offset compCBE1)
	db      0,0,0
	; CBE2
	dd      offset compCBE2
	db      (offset compCBE2_end)-(offset compCBE2)
	db      0,0,0
	; CBE3
	dd      offset compCBE3
	db      (offset compCBE3_end)-(offset compCBE3)
	db      0,0,0
	; CBE4
	dd      offset compCBE4
	db      (offset compCBE4_end)-(offset compCBE4)
	db      0,0,0
	; CBE5
	dd      offset compCBE5
	db      (offset compCBE5_end)-(offset compCBE5)
	db      0,0,0
	; CBE6
	dd      offset compCBE6
	db      (offset compCBE6_end)-(offset compCBE6)
	db      0,0,0
	; CBE7
	dd      offset compCBE7
	db      (offset compCBE7_end)-(offset compCBE7)
	db      0,0,0
	; CBE8
	dd      offset compCBE8
	db      (offset compCBE8_end)-(offset compCBE8)
	db      0,0,0
	; CBE9
	dd      offset compCBE9
	db      (offset compCBE9_end)-(offset compCBE9)
	db      0,0,0
	; CBEA
	dd      offset compCBEA
	db      (offset compCBEA_end)-(offset compCBEA)
	db      0,0,0
	; CBEB
	dd      offset compCBEB
	db      (offset compCBEB_end)-(offset compCBEB)
	db      0,0,0
	; CBEC
	dd      offset compCBEC
	db      (offset compCBEC_end)-(offset compCBEC)
	db      0,0,0
	; CBED
	dd      offset compCBED
	db      (offset compCBED_end)-(offset compCBED)
	db      0,0,0
	; CBEE
	dd      offset compCBEE
	db      (offset compCBEE_end)-(offset compCBEE)
	db      0,0,0
	; CBEF
	dd      offset compCBEF
	db      (offset compCBEF_end)-(offset compCBEF)
	db      0,0,0
	; CBF0
	dd      offset compCBF0
	db      (offset compCBF0_end)-(offset compCBF0)
	db      0,0,0
	; CBF1
	dd      offset compCBF1
	db      (offset compCBF1_end)-(offset compCBF1)
	db      0,0,0
	; CBF2
	dd      offset compCBF2
	db      (offset compCBF2_end)-(offset compCBF2)
	db      0,0,0
	; CBF3
	dd      offset compCBF3
	db      (offset compCBF3_end)-(offset compCBF3)
	db      0,0,0
	; CBF4
	dd      offset compCBF4
	db      (offset compCBF4_end)-(offset compCBF4)
	db      0,0,0
	; CBF5
	dd      offset compCBF5
	db      (offset compCBF5_end)-(offset compCBF5)
	db      0,0,0
	; CBF6
	dd      offset compCBF6
	db      (offset compCBF6_end)-(offset compCBF6)
	db      0,0,0
	; CBF7
	dd      offset compCBF7
	db      (offset compCBF7_end)-(offset compCBF7)
	db      0,0,0
	; CBF8
	dd      offset compCBF8
	db      (offset compCBF8_end)-(offset compCBF8)
	db      0,0,0
	; CBF9
	dd      offset compCBF9
	db      (offset compCBF9_end)-(offset compCBF9)
	db      0,0,0
	; CBFA
	dd      offset compCBFA
	db      (offset compCBFA_end)-(offset compCBFA)
	db      0,0,0
	; CBFB
	dd      offset compCBFB
	db      (offset compCBFB_end)-(offset compCBFB)
	db      0,0,0
	; CBFC
	dd      offset compCBFC
	db      (offset compCBFC_end)-(offset compCBFC)
	db      0,0,0
	; CBFD
	dd      offset compCBFD
	db      (offset compCBFD_end)-(offset compCBFD)
	db      0,0,0
	; CBFE
	dd      offset compCBFE
	db      (offset compCBFE_end)-(offset compCBFE)
	db      0,0,0
	; CBFF
	dd      offset compCBFF
	db      (offset compCBFF_end)-(offset compCBFF)
	db      0,0,0
