include fetchequ.inc

info_table_ed:
	; ED00
	dd      0; offset compED00
	db      0; (offset compED00_end)-(offset compED00)
	db      0,0,0
	; ED01
	dd      0; offset compED01
	db      0; (offset compED01_end)-(offset compED01)
	db      0,0,0
	; ED02
	dd      0; offset compED02
	db      0; (offset compED02_end)-(offset compED02)
	db      0,0,0
	; ED03
	dd      0; offset compED03
	db      0; (offset compED03_end)-(offset compED03)
	db      0,0,0
	; ED04
	dd      0; offset compED04
	db      0; (offset compED04_end)-(offset compED04)
	db      0,0,0
	; ED05
	dd      0; offset compED05
	db      0; (offset compED05_end)-(offset compED05)
	db      0,0,0
	; ED06
	dd      0; offset compED06
	db      0; (offset compED06_end)-(offset compED06)
	db      0,0,0
	; ED07
	dd      0; offset compED07
	db      0; (offset compED07_end)-(offset compED07)
	db      0,0,0
	; ED08
	dd      0; offset compED08
	db      0; (offset compED08_end)-(offset compED08)
	db      0,0,0
	; ED09
	dd      0; offset compED09
	db      0; (offset compED09_end)-(offset compED09)
	db      0,0,0
	; ED0A
	dd      0; offset compED0A
	db      0; (offset compED0A_end)-(offset compED0A)
	db      0,0,0
	; ED0B
	dd      0; offset compED0B
	db      0; (offset compED0B_end)-(offset compED0B)
	db      0,0,0
	; ED0C
	dd      0; offset compED0C
	db      0; (offset compED0C_end)-(offset compED0C)
	db      0,0,0
	; ED0D
	dd      0; offset compED0D
	db      0; (offset compED0D_end)-(offset compED0D)
	db      0,0,0
	; ED0E
	dd      0; offset compED0E
	db      0; (offset compED0E_end)-(offset compED0E)
	db      0,0,0
	; ED0F
	dd      0; offset compED0F
	db      0; (offset compED0F_end)-(offset compED0F)
	db      0,0,0
	; ED10
	dd      0; offset compED10
	db      0; (offset compED10_end)-(offset compED10)
	db      0,0,0
	; ED11
	dd      0; offset compED11
	db      0; (offset compED11_end)-(offset compED11)
	db      0,0,0
	; ED12
	dd      0; offset compED12
	db      0; (offset compED12_end)-(offset compED12)
	db      0,0,0
	; ED13
	dd      0; offset compED13
	db      0; (offset compED13_end)-(offset compED13)
	db      0,0,0
	; ED14
	dd      0; offset compED14
	db      0; (offset compED14_end)-(offset compED14)
	db      0,0,0
	; ED15
	dd      0; offset compED15
	db      0; (offset compED15_end)-(offset compED15)
	db      0,0,0
	; ED16
	dd      0; offset compED16
	db      0; (offset compED16_end)-(offset compED16)
	db      0,0,0
	; ED17
	dd      0; offset compED17
	db      0; (offset compED17_end)-(offset compED17)
	db      0,0,0
	; ED18
	dd      0; offset compED18
	db      0; (offset compED18_end)-(offset compED18)
	db      0,0,0
	; ED19
	dd      0; offset compED19
	db      0; (offset compED19_end)-(offset compED19)
	db      0,0,0
	; ED1A
	dd      0; offset compED1A
	db      0; (offset compED1A_end)-(offset compED1A)
	db      0,0,0
	; ED1B
	dd      0; offset compED1B
	db      0; (offset compED1B_end)-(offset compED1B)
	db      0,0,0
	; ED1C
	dd      0; offset compED1C
	db      0; (offset compED1C_end)-(offset compED1C)
	db      0,0,0
	; ED1D
	dd      0; offset compED1D
	db      0; (offset compED1D_end)-(offset compED1D)
	db      0,0,0
	; ED1E
	dd      0; offset compED1E
	db      0; (offset compED1E_end)-(offset compED1E)
	db      0,0,0
	; ED1F
	dd      0; offset compED1F
	db      0; (offset compED1F_end)-(offset compED1F)
	db      0,0,0
	; ED20
	dd      0; offset compED20
	db      0; (offset compED20_end)-(offset compED20)
	db      0,0,0
	; ED21
	dd      0; offset compED21
	db      0; (offset compED21_end)-(offset compED21)
	db      0,0,0
	; ED22
	dd      0; offset compED22
	db      0; (offset compED22_end)-(offset compED22)
	db      0,0,0
	; ED23
	dd      0; offset compED23
	db      0; (offset compED23_end)-(offset compED23)
	db      0,0,0
	; ED24
	dd      0; offset compED24
	db      0; (offset compED24_end)-(offset compED24)
	db      0,0,0
	; ED25
	dd      0; offset compED25
	db      0; (offset compED25_end)-(offset compED25)
	db      0,0,0
	; ED26
	dd      0; offset compED26
	db      0; (offset compED26_end)-(offset compED26)
	db      0,0,0
	; ED27
	dd      0; offset compED27
	db      0; (offset compED27_end)-(offset compED27)
	db      0,0,0
	; ED28
	dd      0; offset compED28
	db      0; (offset compED28_end)-(offset compED28)
	db      0,0,0
	; ED29
	dd      0; offset compED29
	db      0; (offset compED29_end)-(offset compED29)
	db      0,0,0
	; ED2A
	dd      0; offset compED2A
	db      0; (offset compED2A_end)-(offset compED2A)
	db      0,0,0
	; ED2B
	dd      0; offset compED2B
	db      0; (offset compED2B_end)-(offset compED2B)
	db      0,0,0
	; ED2C
	dd      0; offset compED2C
	db      0; (offset compED2C_end)-(offset compED2C)
	db      0,0,0
	; ED2D
	dd      0; offset compED2D
	db      0; (offset compED2D_end)-(offset compED2D)
	db      0,0,0
	; ED2E
	dd      0; offset compED2E
	db      0; (offset compED2E_end)-(offset compED2E)
	db      0,0,0
	; ED2F
	dd      0; offset compED2F
	db      0; (offset compED2F_end)-(offset compED2F)
	db      0,0,0
	; ED30
	dd      0; offset compED30
	db      0; (offset compED30_end)-(offset compED30)
	db      0,0,0
	; ED31
	dd      0; offset compED31
	db      0; (offset compED31_end)-(offset compED31)
	db      0,0,0
	; ED32
	dd      0; offset compED32
	db      0; (offset compED32_end)-(offset compED32)
	db      0,0,0
	; ED33
	dd      0; offset compED33
	db      0; (offset compED33_end)-(offset compED33)
	db      0,0,0
	; ED34
	dd      0; offset compED34
	db      0; (offset compED34_end)-(offset compED34)
	db      0,0,0
	; ED35
	dd      0; offset compED35
	db      0; (offset compED35_end)-(offset compED35)
	db      0,0,0
	; ED36
	dd      0; offset compED36
	db      0; (offset compED36_end)-(offset compED36)
	db      0,0,0
	; ED37
	dd      0; offset compED37
	db      0; (offset compED37_end)-(offset compED37)
	db      0,0,0
	; ED38
	dd      0; offset compED38
	db      0; (offset compED38_end)-(offset compED38)
	db      0,0,0
	; ED39
	dd      0; offset compED39
	db      0; (offset compED39_end)-(offset compED39)
	db      0,0,0
	; ED3A
	dd      0; offset compED3A
	db      0; (offset compED3A_end)-(offset compED3A)
	db      0,0,0
	; ED3B
	dd      0; offset compED3B
	db      0; (offset compED3B_end)-(offset compED3B)
	db      0,0,0
	; ED3C
	dd      0; offset compED3C
	db      0; (offset compED3C_end)-(offset compED3C)
	db      0,0,0
	; ED3D
	dd      0; offset compED3D
	db      0; (offset compED3D_end)-(offset compED3D)
	db      0,0,0
	; ED3E
	dd      0; offset compED3E
	db      0; (offset compED3E_end)-(offset compED3E)
	db      0,0,0
	; ED3F
	dd      0; offset compED3F
	db      0; (offset compED3F_end)-(offset compED3F)
	db      0,0,0
	; ED40
	dd      offset compED40
	db      (offset compED40_end)-(offset compED40)
	db      0,0,0
	; ED41
	dd      offset compED41
	db      (offset compED41_end)-(offset compED41)
	db      0,0,0
	; ED42
	dd      offset compED42
	db      (offset compED42_end)-(offset compED42)
	db      0,0,0
	; ED43
	dd      offset compED43
	db      (offset compED43_end)-(offset compED43)
	db      FETCHWIMM2,0,0
	; ED44
	dd      offset compED44
	db      (offset compED44_end)-(offset compED44)
	db      0,0,0
	; ED45
	dd      0; offset compED45
	db      0; (offset compED45_end)-(offset compED45)
	db      0,0,0
	; ED46
	dd      0; offset compED46
	db      0; (offset compED46_end)-(offset compED46)
	db      0,0,0
	; ED47
	dd      0; offset compED47
	db      0; (offset compED47_end)-(offset compED47)
	db      0,0,0
	; ED48
	dd      offset compED48
	db      (offset compED48_end)-(offset compED48)
	db      0,0,0
	; ED49
	dd      offset compED49
	db      (offset compED49_end)-(offset compED49)
	db      0,0,0
	; ED4A
	dd      offset compED4A
	db      (offset compED4A_end)-(offset compED4A)
	db      0,0,0
	; ED4B
	dd      offset compED4B
	db      (offset compED4B_end)-(offset compED4B)
	db      FETCHWIMM2,0,0
	; ED4C
	dd      0; offset compED4C
	db      0; (offset compED4C_end)-(offset compED4C)
	db      0,0,0
	; ED4D
	dd      offset compED4D
	db      (offset compED4D_end)-(offset compED4D)
	db      0,0,0
	; ED4E
	dd      0; offset compED4E
	db      0; (offset compED4E_end)-(offset compED4E)
	db      0,0,0
	; ED4F
	dd      0; offset compED4F
	db      0; (offset compED4F_end)-(offset compED4F)
	db      0,0,0
	; ED50
	dd      offset compED50
	db      (offset compED50_end)-(offset compED50)
	db      0,0,0
	; ED51
	dd      offset compED51
	db      (offset compED51_end)-(offset compED51)
	db      0,0,0
	; ED52
	dd      offset compED52
	db      (offset compED52_end)-(offset compED52)
	db      0,0,0
	; ED53
	dd      offset compED53
	db      (offset compED53_end)-(offset compED53)
	db      FETCHWIMM2,0,0
	; ED54
	dd      0; offset compED54
	db      0; (offset compED54_end)-(offset compED54)
	db      0,0,0
	; ED55
	dd      0; offset compED55
	db      0; (offset compED55_end)-(offset compED55)
	db      0,0,0
	; ED56
	dd      offset compED56
	db      (offset compED56_end)-(offset compED56)
	db      0,0,0
	; ED57
	dd      offset compED57
	db      (offset compED57_end)-(offset compED57)
	db      0,0,0
	; ED58
	dd      offset compED58
	db      (offset compED58_end)-(offset compED58)
	db      0,0,0
	; ED59
	dd      offset compED59
	db      (offset compED59_end)-(offset compED59)
	db      0,0,0
	; ED5A
	dd      offset compED5A
	db      (offset compED5A_end)-(offset compED5A)
	db      0,0,0
	; ED5B
	dd      offset compED5B
	db      (offset compED5B_end)-(offset compED5B)
	db      FETCHWIMM2,0,0
	; ED5C
	dd      0; offset compED5C
	db      0; (offset compED5C_end)-(offset compED5C)
	db      0,0,0
	; ED5D
	dd      0; offset compED5D
	db      0; (offset compED5D_end)-(offset compED5D)
	db      0,0,0
	; ED5E
	dd      0; offset compED5E
	db      0; (offset compED5E_end)-(offset compED5E)
	db      0,0,0
	; ED5F
	dd      offset compED5F
	db      (offset compED5F_end)-(offset compED5F)
	db      0,0,0
	; ED60
	dd      offset compED60
	db      (offset compED60_end)-(offset compED60)
	db      0,0,0
	; ED61
	dd      offset compED61
	db      (offset compED61_end)-(offset compED61)
	db      0,0,0
	; ED62  
	dd      offset compED62
	db      (offset compED62_end)-(offset compED62)
	db      0,0,0
	; ED63
	dd      0; offset compED63
	db      0; (offset compED63_end)-(offset compED63)
	db      0,0,0
	; ED64
	dd      0; offset compED64
	db      0; (offset compED64_end)-(offset compED64)
	db      0,0,0
	; ED65
	dd      0; offset compED65
	db      0; (offset compED65_end)-(offset compED65)
	db      0,0,0
	; ED66
	dd      0; offset compED66
	db      0; (offset compED66_end)-(offset compED66)
	db      0,0,0
	; ED67
	dd      offset compED67
	db      (offset compED67_end)-(offset compED67)
	db      0,0,0
	; ED68
	dd      offset compED68
	db      (offset compED68_end)-(offset compED68)
	db      0,0,0
	; ED69
	dd      offset compED69
	db      (offset compED69_end)-(offset compED69)
	db      0,0,0
	; ED6A
	dd      offset compED6A
	db      (offset compED6A_end)-(offset compED6A)
	db      0,0,0
	; ED6B
	dd      0; offset compED6B
	db      0; (offset compED6B_end)-(offset compED6B)
	db      0,0,0
	; ED6C
	dd      0; offset compED6C
	db      0; (offset compED6C_end)-(offset compED6C)
	db      0,0,0
	; ED6D
	dd      0; offset compED6D
	db      0; (offset compED6D_end)-(offset compED6D)
	db      0,0,0
	; ED6E
	dd      0; offset compED6E
	db      0; (offset compED6E_end)-(offset compED6E)
	db      0,0,0
	; ED6F
	dd      offset compED6F
	db      (offset compED6F_end)-(offset compED6F)
	db      0,0,0
	; ED70
	dd      0; offset compED70
	db      0; (offset compED70_end)-(offset compED70)
	db      0,0,0
	; ED71
	dd      0; offset compED71
	db      0; (offset compED71_end)-(offset compED71)
	db      0,0,0
	; ED72
	dd      offset compED72
	db      (offset compED72_end)-(offset compED72)
	db      0,0,0
	; ED73
	dd      offset compED73
	db      (offset compED73_end)-(offset compED73)
	db      FETCHWIMM2,0,0
	; ED74
	dd      0; offset compED74
	db      0; (offset compED74_end)-(offset compED74)
	db      0,0,0
	; ED75
	dd      0; offset compED75
	db      0; (offset compED75_end)-(offset compED75)
	db      0,0,0
	; ED76
	dd      0; offset compED76
	db      0; (offset compED76_end)-(offset compED76)
	db      0,0,0
	; ED77
	dd      0; offset compED77
	db      0; (offset compED77_end)-(offset compED77)
	db      0,0,0
	; ED78
	dd      offset compED78
	db      (offset compED78_end)-(offset compED78)
	db      0,0,0
	; ED79
	dd      offset compED79
	db      (offset compED79_end)-(offset compED79)
	db      0,0,0
	; ED7A
	dd      offset compED7A
	db      (offset compED7A_end)-(offset compED7A)
	db      0,0,0
	; ED7B
	dd      offset compED7B
	db      (offset compED7B_end)-(offset compED7B)
	db      FETCHWIMM2,0,0
	; ED7C
	dd      0; offset compED7C
	db      0; (offset compED7C_end)-(offset compED7C)
	db      0,0,0
	; ED7D
	dd      0; offset compED7D
	db      0; (offset compED7D_end)-(offset compED7D)
	db      0,0,0
	; ED7E
	dd      0; offset compED7E
	db      0; (offset compED7E_end)-(offset compED7E)
	db      0,0,0
	; ED7F
	dd      0; offset compED7F
	db      0; (offset compED7F_end)-(offset compED7F)
	db      0,0,0
	; ED80
	dd      0; offset compED80
	db      0; (offset compED80_end)-(offset compED80)
	db      0,0,0
	; ED81
	dd      0; offset compED81
	db      0; (offset compED81_end)-(offset compED81)
	db      0,0,0
	; ED82
	dd      0; offset compED82
	db      0; (offset compED82_end)-(offset compED82)
	db      0,0,0
	; ED83
	dd      0; offset compED83
	db      0; (offset compED83_end)-(offset compED83)
	db      0,0,0
	; ED84
	dd      0; offset compED84
	db      0; (offset compED84_end)-(offset compED84)
	db      0,0,0
	; ED85
	dd      0; offset compED85
	db      0; (offset compED85_end)-(offset compED85)
	db      0,0,0
	; ED86
	dd      0; offset compED86
	db      0; (offset compED86_end)-(offset compED86)
	db      0,0,0
	; ED87
	dd      0; offset compED87
	db      0; (offset compED87_end)-(offset compED87)
	db      0,0,0
	; ED88
	dd      0; offset compED88
	db      0; (offset compED88_end)-(offset compED88)
	db      0,0,0
	; ED89
	dd      0; offset compED89
	db      0; (offset compED89_end)-(offset compED89)
	db      0,0,0
	; ED8A
	dd      0; offset compED8A
	db      0; (offset compED8A_end)-(offset compED8A)
	db      0,0,0
	; ED8B
	dd      0; offset compED8B
	db      0; (offset compED8B_end)-(offset compED8B)
	db      0,0,0
	; ED8C
	dd      0; offset compED8C
	db      0; (offset compED8C_end)-(offset compED8C)
	db      0,0,0
	; ED8D
	dd      0; offset compED8D
	db      0; (offset compED8D_end)-(offset compED8D)
	db      0,0,0
	; ED8E
	dd      0; offset compED8E
	db      0; (offset compED8E_end)-(offset compED8E)
	db      0,0,0
	; ED8F
	dd      0; offset compED8F
	db      0; (offset compED8F_end)-(offset compED8F)
	db      0,0,0
	; ED90
	dd      0; offset compED90
	db      0; (offset compED90_end)-(offset compED90)
	db      0,0,0
	; ED91
	dd      0; offset compED91
	db      0; (offset compED91_end)-(offset compED91)
	db      0,0,0
	; ED92
	dd      0; offset compED92
	db      0; (offset compED92_end)-(offset compED92)
	db      0,0,0
	; ED93
	dd      0; offset compED93
	db      0; (offset compED93_end)-(offset compED93)
	db      0,0,0
	; ED94
	dd      0; offset compED94
	db      0; (offset compED94_end)-(offset compED94)
	db      0,0,0
	; ED95
	dd      0; offset compED95
	db      0; (offset compED95_end)-(offset compED95)
	db      0,0,0
	; ED96
	dd      0; offset compED96
	db      0; (offset compED96_end)-(offset compED96)
	db      0,0,0
	; ED97
	dd      0; offset compED97
	db      0; (offset compED97_end)-(offset compED97)
	db      0,0,0
	; ED98
	dd      0; offset compED98
	db      0; (offset compED98_end)-(offset compED98)
	db      0,0,0
	; ED99
	dd      0; offset compED99
	db      0; (offset compED99_end)-(offset compED99)
	db      0,0,0
	; ED9A
	dd      0; offset compED9A
	db      0; (offset compED9A_end)-(offset compED9A)
	db      0,0,0
	; ED9B
	dd      0; offset compED9B
	db      0; (offset compED9B_end)-(offset compED9B)
	db      0,0,0
	; ED9C
	dd      0; offset compED9C
	db      0; (offset compED9C_end)-(offset compED9C)
	db      0,0,0
	; ED9D
	dd      0; offset compED9D
	db      0; (offset compED9D_end)-(offset compED9D)
	db      0,0,0
	; ED9E
	dd      0; offset compED9E
	db      0; (offset compED9E_end)-(offset compED9E)
	db      0,0,0
	; ED9F
	dd      0; offset compED9F
	db      0; (offset compED9F_end)-(offset compED9F)
	db      0,0,0
	; EDA0
	dd      offset compEDA0
	db      (offset compEDA0_end)-(offset compEDA0)
	db      0,0,0
	; EDA1
	dd      0; offset compEDA1
	db      0; (offset compEDA1_end)-(offset compEDA1)
	db      0,0,0
	; EDA2
	dd      offset compEDA2
	db      (offset compEDA2_end)-(offset compEDA2)
	db      0,0,0
	; EDA3
	dd      offset compEDA3
	db      (offset compEDA3_end)-(offset compEDA3)
	db      0,0,0
	; EDA4
	dd      0; offset compEDA4
	db      0; (offset compEDA4_end)-(offset compEDA4)
	db      0,0,0
	; EDA5
	dd      0; offset compEDA5
	db      0; (offset compEDA5_end)-(offset compEDA5)
	db      0,0,0
	; EDA6
	dd      0; offset compEDA6
	db      0; (offset compEDA6_end)-(offset compEDA6)
	db      0,0,0
	; EDA7
	dd      0; offset compEDA7
	db      0; (offset compEDA7_end)-(offset compEDA7)
	db      0,0,0
	; EDA8
	dd      offset compEDA8
	db      (offset compEDA8_end)-(offset compEDA8)
	db      0,0,0
	; EDA9
	dd      0; offset compEDA9
	db      0; (offset compEDA9_end)-(offset compEDA9)
	db      0,0,0
	; EDAA
	dd      0; offset compEDAA
	db      0; (offset compEDAA_end)-(offset compEDAA)
	db      0,0,0
	; EDAB
	dd      0; offset compEDAB
	db      0; (offset compEDAB_end)-(offset compEDAB)
	db      0,0,0
	; EDAC
	dd      0; offset compEDAC
	db      0; (offset compEDAC_end)-(offset compEDAC)
	db      0,0,0
	; EDAD
	dd      0; offset compEDAD
	db      0; (offset compEDAD_end)-(offset compEDAD)
	db      0,0,0
	; EDAE
	dd      0; offset compEDAE
	db      0; (offset compEDAE_end)-(offset compEDAE)
	db      0,0,0
	; EDAF
	dd      0; offset compEDAF
	db      0; (offset compEDAF_end)-(offset compEDAF)
	db      0,0,0
	; EDB0
	dd      offset compEDB0
	db      (offset compEDB0_end)-(offset compEDB0)
	db      0,0,0
	; EDB1
	dd      offset compEDB1
	db      (offset compEDB1_end)-(offset compEDB1)
	db      0,0,0
	; EDB2
	dd      0; offset compEDB2
	db      0; (offset compEDB2_end)-(offset compEDB2)
	db      0,0,0
	; EDB3
	dd      0; offset compEDB3
	db      0; (offset compEDB3_end)-(offset compEDB3)
	db      0,0,0
	; EDB4
	dd      0; offset compEDB4
	db      0; (offset compEDB4_end)-(offset compEDB4)
	db      0,0,0
	; EDB5
	dd      0; offset compEDB5
	db      0; (offset compEDB5_end)-(offset compEDB5)
	db      0,0,0
	; EDB6
	dd      0; offset compEDB6
	db      0; (offset compEDB6_end)-(offset compEDB6)
	db      0,0,0
	; EDB7
	dd      0; offset compEDB7
	db      0; (offset compEDB7_end)-(offset compEDB7)
	db      0,0,0
	; EDB8
	dd      offset compEDB8
	db      (offset compEDB8_end)-(offset compEDB8)
	db      0,0,0
	; EDB9
	dd      offset compEDB9
	db      (offset compEDB9_end)-(offset compEDB9)
	db      0,0,0
	; EDBA
	dd      0; offset compEDBA
	db      0; (offset compEDBA_end)-(offset compEDBA)
	db      0,0,0
	; EDBB
	dd      0; offset compEDBB
	db      0; (offset compEDBB_end)-(offset compEDBB)
	db      0,0,0
	; EDBC
	dd      0; offset compEDBC
	db      0; (offset compEDBC_end)-(offset compEDBC)
	db      0,0,0
	; EDBD
	dd      0; offset compEDBD
	db      0; (offset compEDBD_end)-(offset compEDBD)
	db      0,0,0
	; EDBE
	dd      0; offset compEDBE
	db      0; (offset compEDBE_end)-(offset compEDBE)
	db      0,0,0
	; EDBF
	dd      0; offset compEDBF
	db      0; (offset compEDBF_end)-(offset compEDBF)
	db      0,0,0
	; EDC0
	dd      0; offset compEDC0
	db      0; (offset compEDC0_end)-(offset compEDC0)
	db      0,0,0
	; EDC1
	dd      0; offset compEDC1
	db      0; (offset compEDC1_end)-(offset compEDC1)
	db      0,0,0
	; EDC2
	dd      0; offset compEDC2
	db      0; (offset compEDC2_end)-(offset compEDC2)
	db      0,0,0
	; EDC3
	dd      0; offset compEDC3
	db      0; (offset compEDC3_end)-(offset compEDC3)
	db      0,0,0
	; EDC4
	dd      0; offset compEDC4
	db      0; (offset compEDC4_end)-(offset compEDC4)
	db      0,0,0
	; EDC5
	dd      0; offset compEDC5
	db      0; (offset compEDC5_end)-(offset compEDC5)
	db      0,0,0
	; EDC6
	dd      0; offset compEDC6
	db      0; (offset compEDC6_end)-(offset compEDC6)
	db      0,0,0
	; EDC7
	dd      0; offset compEDC7
	db      0; (offset compEDC7_end)-(offset compEDC7)
	db      0,0,0
	; EDC8
	dd      0; offset compEDC8
	db      0; (offset compEDC8_end)-(offset compEDC8)
	db      0,0,0
	; EDC9
	dd      0; offset compEDC9
	db      0; (offset compEDC9_end)-(offset compEDC9)
	db      0,0,0
	; EDCA
	dd      0; offset compEDCA
	db      0; (offset compEDCA_end)-(offset compEDCA)
	db      0,0,0
	; EDCB
	dd      0; offset compEDCB
	db      0; (offset compEDCB_end)-(offset compEDCB)
	db      0,0,0
	; EDCC
	dd      0; offset compEDCC
	db      0; (offset compEDCC_end)-(offset compEDCC)
	db      0,0,0
	; EDCD
	dd      0; offset compEDCD
	db      0; (offset compEDCD_end)-(offset compEDCD)
	db      0,0,0
	; EDCE
	dd      0; offset compEDCE
	db      0; (offset compEDCE_end)-(offset compEDCE)
	db      0,0,0
	; EDCF
	dd      0; offset compEDCF
	db      0; (offset compEDCF_end)-(offset compEDCF)
	db      0,0,0
	; EDD0
	dd      0; offset compEDD0
	db      0; (offset compEDD0_end)-(offset compEDD0)
	db      0,0,0
	; EDD1
	dd      0; offset compEDD1
	db      0; (offset compEDD1_end)-(offset compEDD1)
	db      0,0,0
	; EDD2
	dd      0; offset compEDD2
	db      0; (offset compEDD2_end)-(offset compEDD2)
	db      0,0,0
	; EDD3
	dd      0; offset compEDD3
	db      0; (offset compEDD3_end)-(offset compEDD3)
	db      0,0,0
	; EDD4
	dd      0; offset compEDD4
	db      0; (offset compEDD4_end)-(offset compEDD4)
	db      0,0,0
	; EDD5
	dd      0; offset compEDD5
	db      0; (offset compEDD5_end)-(offset compEDD5)
	db      0,0,0
	; EDD6
	dd      0; offset compEDD6
	db      0; (offset compEDD6_end)-(offset compEDD6)
	db      0,0,0
	; EDD7
	dd      0; offset compEDD7
	db      0; (offset compEDD7_end)-(offset compEDD7)
	db      0,0,0
	; EDD8
	dd      0; offset compEDD8
	db      0; (offset compEDD8_end)-(offset compEDD8)
	db      0,0,0
	; EDD9
	dd      0; offset compEDD9
	db      0; (offset compEDD9_end)-(offset compEDD9)
	db      0,0,0
	; EDDA
	dd      0; offset compEDDA
	db      0; (offset compEDDA_end)-(offset compEDDA)
	db      0,0,0
	; EDDB
	dd      0; offset compEDDB
	db      0; (offset compEDDB_end)-(offset compEDDB)
	db      0,0,0
	; EDDC
	dd      0; offset compEDDC
	db      0; (offset compEDDC_end)-(offset compEDDC)
	db      0,0,0
	; EDDD
	dd      0; offset compEDDD
	db      0; (offset compEDDD_end)-(offset compEDDD)
	db      0,0,0
	; EDDE
	dd      0; offset compEDDE
	db      0; (offset compEDDE_end)-(offset compEDDE)
	db      0,0,0
	; EDDF
	dd      0; offset compEDDF
	db      0; (offset compEDDF_end)-(offset compEDDF)
	db      0,0,0
	; EDE0
	dd      0; offset compEDE0
	db      0; (offset compEDE0_end)-(offset compEDE0)
	db      0,0,0
	; EDE1
	dd      0; offset compEDE1
	db      0; (offset compEDE1_end)-(offset compEDE1)
	db      0,0,0
	; EDE2
	dd      0; offset compEDE2
	db      0; (offset compEDE2_end)-(offset compEDE2)
	db      0,0,0
	; EDE3
	dd      0; offset compEDE3
	db      0; (offset compEDE3_end)-(offset compEDE3)
	db      0,0,0
	; EDE4
	dd      0; offset compEDE4
	db      0; (offset compEDE4_end)-(offset compEDE4)
	db      0,0,0
	; EDE5
	dd      0; offset compEDE5
	db      0; (offset compEDE5_end)-(offset compEDE5)
	db      0,0,0
	; EDE6
	dd      0; offset compEDE6
	db      0; (offset compEDE6_end)-(offset compEDE6)
	db      0,0,0
	; EDE7
	dd      0; offset compEDE7
	db      0; (offset compEDE7_end)-(offset compEDE7)
	db      0,0,0
	; EDE8
	dd      0; offset compEDE8
	db      0; (offset compEDE8_end)-(offset compEDE8)
	db      0,0,0
	; EDE9
	dd      0; offset compEDE9
	db      0; (offset compEDE9_end)-(offset compEDE9)
	db      0,0,0
	; EDEA
	dd      0; offset compEDEA
	db      0; (offset compEDEA_end)-(offset compEDEA)
	db      0,0,0
	; EDEB
	dd      0; offset compEDEB
	db      0; (offset compEDEB_end)-(offset compEDEB)
	db      0,0,0
	; EDEC
	dd      0; offset compEDEC
	db      0; (offset compEDEC_end)-(offset compEDEC)
	db      0,0,0
	; EDED
	dd      0; offset compEDED
	db      0; (offset compEDED_end)-(offset compEDED)
	db      0,0,0
	; EDEE
	dd      0; offset compEDEE
	db      0; (offset compEDEE_end)-(offset compEDEE)
	db      0,0,0
	; EDEF
	dd      0; offset compEDEF
	db      0; (offset compEDEF_end)-(offset compEDEF)
	db      0,0,0
	; EDF0
	dd      0; offset compEDF0
	db      0; (offset compEDF0_end)-(offset compEDF0)
	db      0,0,0
	; EDF1
	dd      0; offset compEDF1
	db      0; (offset compEDF1_end)-(offset compEDF1)
	db      0,0,0
	; EDF2
	dd      0; offset compEDF2
	db      0; (offset compEDF2_end)-(offset compEDF2)
	db      0,0,0
	; EDF3
	dd      0; offset compEDF3
	db      0; (offset compEDF3_end)-(offset compEDF3)
	db      0,0,0
	; EDF4
	dd      0; offset compEDF4
	db      0; (offset compEDF4_end)-(offset compEDF4)
	db      0,0,0
	; EDF5
	dd      0; offset compEDF5
	db      0; (offset compEDF5_end)-(offset compEDF5)
	db      0,0,0
	; EDF6
	dd      0; offset compEDF6
	db      0; (offset compEDF6_end)-(offset compEDF6)
	db      0,0,0
	; EDF7
	dd      0; offset compEDF7
	db      0; (offset compEDF7_end)-(offset compEDF7)
	db      0,0,0
	; EDF8
	dd      0; offset compEDF8
	db      0; (offset compEDF8_end)-(offset compEDF8)
	db      0,0,0
	; EDF9
	dd      0; offset compEDF9
	db      0; (offset compEDF9_end)-(offset compEDF9)
	db      0,0,0
	; EDFA
	dd      0; offset compEDFA
	db      0; (offset compEDFA_end)-(offset compEDFA)
	db      0,0,0
	; EDFB
	dd      0; offset compEDFB
	db      0; (offset compEDFB_end)-(offset compEDFB)
	db      0,0,0
	; EDFC
	dd      0; offset compEDFC
	db      0; (offset compEDFC_end)-(offset compEDFC)
	db      0,0,0
	; EDFD
	dd      0; offset compEDFD
	db      0; (offset compEDFD_end)-(offset compEDFD)
	db      0,0,0
	; EDFE
	dd      0; offset compEDFE
	db      0; (offset compEDFE_end)-(offset compEDFE)
	db      0,0,0
	; EDFF
	dd      0; offset compEDFF
	db      0; (offset compEDFF_end)-(offset compEDFF)
	db      0,0,0
