extrn printmsg:near
extrn printasc:near
extrn printhex2:near
extrn printhex4:near
extrn printspace:near
extrn crlf: near
extrn getchar: near
extrn gethex4: near
extrn testkbd: near
extrn setgraphmode: near
extrn settextmode: near
extrn toupper: near
extrn open_file: near
extrn read_file: near
extrn turnon_irq: near
extrn turnoff_irq: near
extrn turnon_kb_irq: near
extrn turnoff_kb_irq: near
extrn read_size_file: near
extrn blit: near
extrn exit_now: dword
extrn framerate: dword
extrn on_off: dword
extrn set_border_color: near
extrn videomode: dword
extrn measurespeed: near
extrn clockrate: byte
extrn printdecimal: near
extrn bargraphmode: dword
