OBJECTS = pmode.o brmsx.o io.o debug.o patch.o \
	  z80.o z80cb.o z80dd.o z80ed.o z80fd.o \
	  print.o printcb.o
TASMFLAGS = /ml /m2 /q /la

all : brmsx.exe brmsxwin.exe

brmsx.exe : $(OBJECTS) vdpdos.o
	tlink /3 /x $^, $@

brmsxwin.exe : $(OBJECTS) vdpwin.o
	tlink /3 /x $^, $@

vdpdos.o : vdp.asm
	tasm $(TASMFLAGS) /dDOS $^,$@

vdpwin.o : vdp.asm
	tasm $(TASMFLAGS) /dWIN $^,$@

%.o : %.asm
	tasm $(TASMFLAGS) $^,$@

z80.o : z80.asm opcode.inc
	tasm $(TASMFLAGS) z80.asm,$@

clean :
	del *.o
	del *.exe
	del *.lst
	del *.inn        
	del *.pro
	del cart1.rom
