OBJECTS = pmode.o brmsx.o debug.o patch.o \
	  io.o pentium.o saveload.o gui.o blit.o \
	  z80.o z80cb.o z80dd.o z80ed.o z80fd.o \
	  print.o printcb.o
TASMFLAGS = /ml /m2 /q /la
ECHO = rbecho

all : rbecho.exe brmsx.exe brmsxwin.exe brmsxmmx.exe

fast: changemode all

changemode:
TASMFLAGS= /ml /m2 /q

rbecho.exe: rbecho.c
	gcc $^ -o $@ 

brmsx.exe : $(OBJECTS) vdpdos.o
	$(ECHO) objects.lst $^
	tlink /3 /x @objects.lst , $@

brmsxwin.exe : $(OBJECTS) vdpwin.o
	$(ECHO) objects.lst $^
	tlink /3 /x @objects.lst , $@

brmsxmmx.exe : $(OBJECTS) vdpmmx.o
	$(ECHO) objects.lst $^
	tlink /3 /x @objects.lst , $@

vdpdos.o : vdp.asm
	tasm $(TASMFLAGS) /dDOS $^,$@

vdpwin.o : vdp.asm
	tasm $(TASMFLAGS) /dWIN $^,$@

vdpmmx.o : vdp.asm
	tasm $(TASMFLAGS) /dMMX $^,$@

%.o : %.asm
	tasm $(TASMFLAGS) $^,$@

z80.o : z80.asm opcode.inc
	tasm $(TASMFLAGS) z80.asm,$@

clean :
	del *.o
	del *.exe
	del *.lst
	del cart1.rom
	del brmsx.sta
